'use strict';
const $=id=>document.getElementById(id),E=TripCore.esc;
const REGION_NAMES={portland:'Portland / Coast',ride:'Hwy 1',bay:'Bay Area',la:'Los Angeles'};
const KINDS={must:'MUST · 核心',optional:'OPTIONAL · 可选','if-time':'IF TIME · 有空再去',rain:'RAIN · 雨备'};
const SAFETY={normal:'🟡 NORMAL · 常规收好',empty:'🟠 EMPTY CAR · 清空可见物',gear:'🔴 TAKE ALL GEAR · 器材随身'};
const Store={read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f;}catch(_){return f;}},write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch(_){toast('无法保存到本机；本次操作仅在当前页面有效。');return false;}}};
let states=TripCore.normalizeState(Store.read('tp-stops-v2',{}));
let starts=Store.read('tp-starts-v2',{});if(!starts||typeof starts!=='object'||Array.isArray(starts))starts={};
let todoState=Store.read('tp-todos-v2',{});if(!todoState||typeof todoState!=='object'||Array.isArray(todoState))todoState={};
let packed=Store.read('us-trip-pack-v1',{});if(!packed||typeof packed!=='object'||Array.isArray(packed))packed={};
let privateData=Store.read('tp-private-v1',{version:1,entries:[]});if(!privateData||!Array.isArray(privateData.entries))privateData={version:1,entries:[]};
let selectedDate,view='today',activeTool='flights',autoDate=true,lastAutomaticDate,toastTimer;
function travelClock(now=new Date()){
 // Use the trip's time zones instead of the phone's home time zone.
 const utc=now.toISOString();const zone=utc<'2026-09-27T03:10:00.000Z'?'Asia/Shanghai':utc>='2026-10-11T20:00:00.000Z'?'Asia/Tokyo':'America/Los_Angeles';return {...TripCore.clock(now,zone),zone};
}
function initialDate(){const date=travelClock().date;return TP.days.some(d=>d.d===date)?date:date<TP.days[0].d?TP.days[0].d:TP.days.at(-1).d;}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
function nav(s){return s.q?'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(s.q)+'&travelmode=driving':null;}
function navLink(s,primary=false){const u=nav(s);return u?`<a class="${primary?'nav-primary':'btn'}" href="${E(u)}" target="_blank" rel="noopener noreferrer" aria-label="导航到 ${E(s.t)}">🧭 ${s.privateLocation?'导航到城区':'导航'}</a>`:'<span class="muted">此项无导航地点</span>';}
function photo(s){const p=TP.photos[s.t];return p?`<details class="shot"><summary>地点照片</summary><a href="photos/${E(p.f)}" target="_blank" rel="noopener"><img class="sp-img" loading="lazy" src="photos/${E(p.f)}" alt="${E(s.t)}"></a><div class="sp-cr">${E(p.by)} · <a href="${E(p.page)}" target="_blank" rel="noopener noreferrer">${E(p.lic)}</a></div></details>`:'';}
function safety(s){return `<details class="safety"><summary>${SAFETY[s.safety||'normal']}</summary><p>${E(s.parking||'随身带走证件与贵重物品，遵守现场停车标识。')} 这是物品保管提示，不代表当地安全评级。</p></details>`;}
function shot(s){return s.shots?.length?`<details class="shot"><summary>🎥 SHOT · 拍摄提示</summary><ul>${s.shots.map(x=>`<li>${E(x)}</li>`).join('')}</ul></details>`:'';}
function actions(s){const st=states[s.id];return `<div class="stop-actions">${navLink(s)}${st?`<button class="btn" data-stop="${E(s.id)}" data-state="undo">撤销${st==='done'?'完成':'跳过'}</button>`:`<button class="btn" data-stop="${E(s.id)}" data-state="done">已完成</button><button class="btn" data-stop="${E(s.id)}" data-state="skipped">跳过</button>`}</div>`;}
function stopHTML(s,{map=false}={}){
 const st=states[s.id],stopDate=s.id.slice(0,10);return `<article class="stop-card ${st==='done'?'completed':st==='skipped'?'skipped':''}" id="${map?'map':'today'}-stop-${E(s.id)}"><div class="stop-top"><span class="stop-time">${E(s.time)}</span><span class="tag-kind ${E(s.kind)}">${KINDS[s.kind]||KINDS.must}</span></div>${map?`<button class="map-spot" data-map-focus="${E(s.id)}"><h3>${E(s.t)}</h3></button>`:`<h3>${E(s.t)}</h3>`}${st?`<span class="status-label">${st==='done'?'✓ 已完成':'↷ 已跳过'}</span>`:''}<p class="muted">${E(s.why)}</p>${s.deadline?`<p class="pressure">${E(s.deadlineLabel||'最晚出发')} ${E(s.deadline)} · ${E(TripCore.remaining(stopDate,s.deadline,new Date(),s.timezone||'America/Los_Angeles'))}</p>`:''}${s.travel?`<p class="muted">${s.transit?'本段':'从上一站'}计划预留约 ${s.travel} 分钟 · 非实时车程</p>`:''}${s.sunset?'<p class="muted">🌅 日落与低潮分开核对；精确日落时刻见当天条件卡。</p>':''}${safety(s)}${actions(s)}${!st?`<button class="text-btn" data-start="${E(s.id)}">从这一站继续</button>`:''}${shot(s)}${photo(s)}</article>`;
}
function doneTodo(t){return Object.hasOwn(todoState,t.id)?todoState[t.id]===true:t.p==='done';}
function todoHTML(t,short=false){return `<label class="${short?'due-item':'todo-row'} ${doneTodo(t)?'done':''}"><input type="checkbox" data-todo="${E(t.id)}" ${doneTodo(t)?'checked':''}><span>${E(t.x)}${short?'':`<br><small class="muted">相关日期 ${E(t.from.slice(5))} – ${E(t.due.slice(5))}</small>`}</span></label>`;}
function selectDate(date,automatic=false){if(!TP.plans[date])return;selectedDate=date;autoDate=automatic;$('day-select').value=date;renderToday();renderTrip();if(view==='map')TripMap.show(TP.plans[date].region,date);TripConditions.load(date);}
function renderToday(){
 const d=TP.days.find(x=>x.d===selectedDate),plan=TP.plans[selectedDate],clock=travelClock(),isToday=selectedDate===clock.date;
 $('today-heading').innerHTML=`<p class="eyebrow">${isToday?'TODAY':selectedDate<clock.date?'PAST · 行程回顾':'PLAN · 日期预览'} · ${E(selectedDate)}</p><h2 class="today-title">${E(d.t)}</h2><p class="muted">${E(d.loc)} · ${E(d.timezone)}${!isToday?' · 当前不在这一天，时间压力提示已停用':''}</p>`;
 const next=TripCore.next(plan.stops,states,starts[selectedDate]);const before=starts[selectedDate]?plan.stops.slice(0,plan.stops.findIndex(s=>s.id===starts[selectedDate])).filter(s=>!states[s.id]):[];
 const pending=plan.stops.filter(s=>!states[s.id]).length,done=plan.stops.filter(s=>states[s.id]==='done').length,skipped=plan.stops.filter(s=>states[s.id]==='skipped').length;
 const pressure=next&&isToday?TripCore.pressure(selectedDate,next.time,new Date(),next.timezone||d.timezone):'';
 $('now-card').innerHTML=next?`<div class="now-card"><div class="eyebrow">${isToday?'NOW · 下一站':'NEXT · 计划下一站'}</div><h2>${E(next.t)}</h2><div class="now-meta">计划 ${E(next.time)}${next.travel?` · ${next.transit?'本段':'从上一站'}预留约 ${next.travel} min`:' · 实时车程请看导航'}</div>${pressure?`<div class="pressure">${E(pressure)}</div>`:''}<p class="muted">${E(next.why)}</p>${next.deadline?`<div class="pressure">${E(next.deadlineLabel||'最晚出发')} ${E(next.deadline)} ${isToday?E(TripCore.remaining(selectedDate,next.deadline,new Date(),next.timezone||d.timezone)):''}</div>`:''}${safety(next)}${navLink(next,true)}<div class="stop-actions"><button class="btn" data-stop="${E(next.id)}" data-state="done">✓ 已完成</button><button class="btn" data-stop="${E(next.id)}" data-state="skipped">跳过此站</button><button class="btn" data-view="map">当天地图</button></div><p class="muted">完成 ${done} · 跳过 ${skipped} · 待确认 ${pending}。时间经过不会自动标记完成；可选和雨备站留在下方。</p>${before.length?`<p class="muted">早前还有 ${before.length} 站待确认。</p><button class="text-btn" id="review-earlier">回到最早未完成站</button>`:''}</div>`:`<div class="now-card"><p class="eyebrow">${pending?'核心路线已处理':'DAY COMPLETE'}</p><h2>${pending?'休息一下，或选择下方可选站':'今天的站点已全部处理'}</h2><p class="muted">完成 ${done} · 跳过 ${skipped}${pending?` · 仍有 ${pending} 站待确认`:''}</p>${starts[selectedDate]?'<button class="text-btn" id="review-earlier">查看早前未完成站</button>':''}</div>`;
 const due=TP.todos.filter(t=>!doneTodo(t)&&t.from<=selectedDate&&t.due>=selectedDate);$('due-todos').innerHTML=due.length?`<div class="panel"><h3>这一天要留意</h3>${due.map(t=>todoHTML(t,true)).join('')}</div>`:'';
 $('today-stops').innerHTML=`<div class="panel-title"><h2>当天站点</h2><span class="muted">${done+skipped} / ${plan.stops.length} 已处理</span></div>`+plan.stops.map(s=>stopHTML(s)).join('');
 renderPrivate();TripConditions.render(selectedDate);
}
function renderTrip(){const today=travelClock().date;$('timeline').innerHTML=TP.days.map(d=>`<details class="plan-card ${d.d===today?'today':d.d<today?'past':'future'}" ${d.d===selectedDate?'open':''}><summary><span class="plan-date">${E(d.d.slice(5))} · ${E(d.timezone)}</span><br>${E(d.t)}</summary><div><p class="muted">${E(d.loc)}</p><ul class="items">${d.items.map(x=>`<li><b>${E(x[0])}</b> ${E(x[1])}</li>`).join('')}</ul><p class="muted">🛏 ${E(d.stay||'')} ${d.mv?' · '+E(d.mv):''}</p><button class="btn" data-open-day="${d.d}">打开当天 · 导航与状态</button></div></details>`).join('');}
function renderTravel(){
 $('flights').innerHTML=TP.flights.map(f=>`<div class="fcard"><div class="f-date">${E(f.dt)}</div><h3>${E(f.rt)}</h3><p>${E(f.no)}</p><div class="f-times"><div>起飞<b>${E(f.dep)}</b></div><div>到达<b>${E(f.arr)}</b></div></div><p class="f-note">${E(f.note.replace(/<[^>]*>/g,''))}</p></div>`).join('');
 $('cars').innerHTML=TP.cars.map(c=>`<div class="fcard"><div class="f-date">${E(c.dt)}</div><h3>${E(c.rt)}</h3><p>${E(c.no)}</p><p class="muted">取 ${E(c.dep)} · 还 ${E(c.arr)}</p><p class="f-note">${E(c.note.replace(/<br>/g,'\n').replace(/<[^>]*>/g,''))}</p><a class="pop-nav" target="_blank" rel="noopener noreferrer" href="${E(nav(c))}">🧭 取还车导航</a></div>`).join('');
}
function renderPack(){let total=0,done=0;$('pack').innerHTML=TP.pack.map((c,ci)=>`<div class="pcat"><h3>${E(c.cat)}</h3>${c.items.map((text,ii)=>{const key=ci+'-'+ii;total++;if(packed[key])done++;return `<label class="pitem ${packed[key]?'done':''}"><input type="checkbox" data-pack="${key}" ${packed[key]?'checked':''}><span>${E(text)}</span></label>`;}).join('')}</div>`).join('');$('pack-progress').innerHTML=`<p class="muted">已打包 ${done} / ${total} · 本机保存</p><div class="progress-track"><i style="width:${done/total*100}%"></i></div>`;}
function renderTodos(){$('todos').innerHTML=TP.todos.map(t=>todoHTML(t)).join('');}
function privateEntry(entry){return `<div class="private-entry"><strong>${E(entry.date)} ${E(entry.title)}</strong><br>${E(entry.details)}</div>`;}
function renderPrivate(){$('private-status').textContent=privateData.entries.length?`已导入 ${privateData.entries.length} 条，仅当前设备可见。`:'尚未导入。';$('private-list').innerHTML=privateData.entries.map(privateEntry).join('');const entries=privateData.entries.filter(x=>x.date===selectedDate);$('today-private').innerHTML=entries.length?entries.map(privateEntry).join(''):'<p class="muted">尚未导入这一天的私人详情，请在「更多 → 本机详情」导入备份，或打开原预订平台。</p>';}
function showView(v){if(!['today','trip','map','more'].includes(v))return;view=v;document.querySelectorAll('main>section').forEach(s=>s.classList.toggle('on',s.id==='v-'+v));document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('on',b.dataset.view===v);if(b.dataset.view===v)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(v==='map')TripMap.show(TP.plans[selectedDate].region,selectedDate);if(v==='more')showTool(activeTool);window.scrollTo({top:0,behavior:'instant'});}
function showTool(t){activeTool=t;document.querySelectorAll('.tool-panel').forEach(p=>p.hidden=p.id!=='tool-'+t);document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('on',b.dataset.tool===t));}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function stopById(id){return Object.values(TP.plans).flatMap(p=>p.stops).find(s=>s.id===id);}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view)showView(b.dataset.view);
 if(b.dataset.tool)showTool(b.dataset.tool);
 if(b.dataset.openDay){selectDate(b.dataset.openDay);showView('today');}
 if(b.dataset.stop){if(!stopById(b.dataset.stop))return;if(b.dataset.state==='undo')delete states[b.dataset.stop];else states[b.dataset.stop]=b.dataset.state;Store.write('tp-stops-v2',states);renderToday();TripMap.refresh();toast(b.dataset.state==='undo'?'已撤销':b.dataset.state==='done'?'已完成，下一站已更新':'已跳过，可随时撤销');}
 if(b.dataset.start){const s=stopById(b.dataset.start);const date=Object.keys(TP.plans).find(d=>TP.plans[d].stops.some(x=>x.id===s.id));if(!date)return;selectedDate=date;starts[date]=s.id;Store.write('tp-starts-v2',starts);$('day-select').value=date;renderToday();showView('today');toast('已从这一站继续；早前站点未自动标记完成');}
 if(b.id==='review-earlier'){delete starts[selectedDate];Store.write('tp-starts-v2',starts);renderToday();}
 if(b.dataset.mapFocus)TripMap.focus(b.dataset.mapFocus);
 if(b.id==='go-today'){selectDate(initialDate(),true);showView('today');}
 if(b.id==='export-ics')download('tidepool-2026.ics',TripCore.ics(TP.days),'text/calendar;charset=utf-8');
 if(b.id==='print'){document.querySelectorAll('#timeline details').forEach(x=>x.open=true);window.print();}
 if(b.id==='pack-reset'&&confirm('清空装备勾选？行程完成状态不会受影响。')){packed={};Store.write('us-trip-pack-v1',packed);renderPack();}
 if(b.id==='clear-private'&&confirm('清除当前浏览器保存的私人详情？请先保留自己的备份文件。')){privateData={version:1,entries:[]};Store.write('tp-private-v1',privateData);renderPrivate();}
 if(b.id==='export-private')download('tidepool-private-details.json',JSON.stringify(privateData,null,2),'application/json');
 if(b.id==='refresh-conditions')TripConditions.load(selectedDate,true);
});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='day-select')selectDate(el.value);if(el.dataset.todo){todoState[el.dataset.todo]=el.checked;Store.write('tp-todos-v2',todoState);renderTodos();renderToday();}if(el.dataset.pack){packed[el.dataset.pack]=el.checked;Store.write('us-trip-pack-v1',packed);renderPack();}});
$('import-private').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('文件太大');const data=JSON.parse(await f.text());if(data.version!==1||!Array.isArray(data.entries)||data.entries.length>300||!data.entries.every(x=>x&&typeof x.date==='string'&&typeof x.title==='string'&&typeof x.details==='string'&&x.details.length<50000))throw Error('格式不正确');privateData={version:1,entries:data.entries.map(({date,title,details})=>({date,title,details}))};const saved=Store.write('tp-private-v1',privateData);renderPrivate();toast(saved?'已导入本机详情，没有上传':'已载入，但本机存储不可用，请保留文件');}catch(_){toast('导入失败，请选择 Tidepool 的私人详情 JSON 备份。');}e.target.value='';});
// Keep the existing iPhone Maps handoff, with a normal web link as fallback.
document.addEventListener('click',e=>{if(!/iPhone|iPad|iPod/.test(navigator.userAgent))return;const a=e.target.closest('a');if(!a)return;let u;try{u=new URL(a.href);}catch(_){return;}if(u.hostname!=='www.google.com'||u.pathname!=='/maps/dir/')return;const dest=u.searchParams.get('destination');if(!dest)return;e.preventDefault();let hidden=false;const listener=()=>{if(document.hidden)hidden=true;};document.addEventListener('visibilitychange',listener);location.href='comgooglemaps://?daddr='+encodeURIComponent(dest)+'&directionsmode=driving';setTimeout(()=>{document.removeEventListener('visibilitychange',listener);if(!hidden&&!document.hidden)location.href=a.href;},1600);});
function tick(){const c=travelClock();$('local-clock').textContent=`${c.date.slice(5)} ${c.time} · ${c.zone==='America/Los_Angeles'?'美西时间':c.zone==='Asia/Tokyo'?'日本时间':'北京时间'}`;$('network').textContent=navigator.onLine?'在线':'离线';if(autoDate&&lastAutomaticDate!==c.date){lastAutomaticDate=c.date;selectDate(initialDate(),true);}else if(view==='today'&&!document.querySelector('#v-today details[open]')&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))renderToday();}
window.addEventListener('online',()=>{tick();TripConditions.load(selectedDate);});window.addEventListener('offline',tick);
window.addEventListener('storage',e=>{if(e.key==='tp-stops-v2'){states=TripCore.normalizeState(Store.read(e.key,{}));renderToday();TripMap.refresh();}if(e.key==='tp-todos-v2'){todoState=Store.read(e.key,{});renderTodos();renderToday();}if(e.key==='us-trip-pack-v1'){packed=Store.read(e.key,{});renderPack();}});
$('day-select').innerHTML=TP.days.map(d=>`<option value="${d.d}">${E(d.d.slice(5))} · ${E(d.t)}</option>`).join('');selectedDate=initialDate();lastAutomaticDate=travelClock().date;$('day-select').value=selectedDate;
$('footer').textContent=`Trip plan updated ${new Intl.DateTimeFormat('zh-CN',{timeZone:'America/Los_Angeles',dateStyle:'short',timeStyle:'short'}).format(new Date(TP.meta.updatedAt))} · 美西时间 · ${TP.meta.version}`;
renderTravel();renderPack();renderTodos();renderTrip();renderToday();TripConditions.renderSources();tick();TripConditions.load(selectedDate);setInterval(tick,60000);
if(location.hash==='#more'){showView('more');showTool('private');}
