window.TripConditions=(()=>{
 const sources=[
 {id:'fuel',title:'俄勒冈加油 · 已纠正旧信息',type:'已核对 2026-09-29',note:'允许自助加油，按站内自助 / 人工泵标识操作。',url:'https://www.oregon.gov/osfm/pages/self-serve-fueling.aspx'},
 {id:'southwest',title:'Southwest 座位 · 已纠正旧信息',type:'已核对 2026-09-29',note:'2026-01-27 起采用分配座位；按票种和航空公司 App 确认。',url:'https://www.southwest.com/customer-enhancements/assigned-seating/'},
 {id:'or-roads',title:'Oregon 道路 · TripCheck',type:'当天确认',note:'I-84 / 历史公路 / US-30 / US-101 / US-26 实时路况。',url:'https://www.tripcheck.com/'},
 {id:'ca-roads',title:'California 道路 · Caltrans',type:'当天确认',note:'Hwy 1 / CA-17 是否开放，不以路线示意线判断通行。',url:'https://quickmap.dot.ca.gov/'},
 {id:'ecola',title:'Ecola State Park',type:'当天确认',note:'道路与步道可能分别关闭，出发前查看官方 Alerts；关闭则取消园内停留。',url:'https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=136'},
 {id:'gorge',title:'Columbia River Gorge · USFS',type:'当天确认',note:'瀑布步道、停车与可能的预约要求。',url:'https://www.fs.usda.gov/r06/columbiarivergorge'},
 {id:'apple',title:'Apple Pioneer Place',type:'已核对 2026-09-29',note:'计划 10:00 到店，耳塞库存仍需现场确认。',url:'https://www.apple.com/retail/pioneerplace/'},
 {id:'powells',title:'Powell’s 店址与开放',type:'当天确认',note:'普通卖场与 Rare Book Room 开放可能不同。',url:'https://www.powells.com/locations'},
 {id:'flavel',title:'Flavel House Museum',type:'已核对 2026-09-29',note:'5–9 月最后入场 16:30，17:00 闭馆；当天如有临时变化以馆方为准。',url:'https://astoriamuseums.org/explore/flavel-house-museum/'},
 {id:'film',title:'Oregon Film Museum',type:'当天确认',note:'参观时段与票价请查馆方。',url:'https://astoriamuseums.org/explore/oregon-film-museum/'},
 {id:'column',title:'Astoria Column',type:'当天确认',note:'登塔、停车与日落前开放情况。',url:'https://astoriacolumn.org/'},
 {id:'tide',title:'Cannon Beach 潮汐',type:'当天确认',note:'当地游客中心提供 NOAA 参考潮表；潮汐、海浪与现场通行需要一起判断，日落不等于低潮。',url:'https://www.cannonbeach.org/things-to-do/beaches-and-parks/tide-charts/'},
 {id:'surf',title:'Santa Cruz Surfing Museum',type:'当天确认',note:'旧计划中的营业时间未作当天保证，关门就只看 West Cliff 海景。',url:'https://www.santacruz.org/listings/santa-cruz-surfing-museum/'},
 {id:'laguna',title:'WeatherTech Raceway Laguna Seca',type:'当天确认',note:'商店营业先问 (831) 242-8201，未确认不专程赶去。',url:'https://www.co.monterey.ca.us/government/government-links/weathertech-raceway'},
 {id:'lobos',title:'Point Lobos',type:'当天确认',note:'停车费、开放与步道限制查 California State Parks。',url:'https://www.parks.ca.gov/?page_id=571'},
 {id:'mcway',title:'Julia Pfeiffer Burns / McWay',type:'当天确认',note:'观景步道与停车可能封闭；不以旧行程描述作为进入依据。',url:'https://www.parks.ca.gov/?page_id=578'},
 {id:'golden-gate',title:'Golden Gate Bridge 收费',type:'当天确认',note:'过桥费与租车公司的代收费用分开核对。',url:'https://www.goldengate.org/bridge/tolls-payment/'},
 {id:'muir',title:'Muir Woods 预约',type:'当天确认',note:'只有预约确认后才把此项加入当天路线。',url:'https://www.nps.gov/muwo/planyourvisit/reservations.htm'}
 ];
 const inFlight=new Map(),errors=new Map();
 function config(date){const r=TP.plans[date].region;let ll=r==='portland'?[45.52,-122.67]:r==='ride'?[36.62,-121.93]:r==='la'?[33.96,-118.45]:[37.52,-122.28];let place=REGION_NAMES[r];if(date==='2026-09-29'){ll=[46.1813,-123.8176];place='Astoria';}if(date==='2026-09-30'||date==='2026-10-01'){ll=[45.89,-123.96];place='Cannon Beach';}if(date==='2026-10-06'){ll=[36.27,-121.81];place='Big Sur';}if(date==='2026-10-11'){ll=[33.94,-118.40];place='LAX';}if(date==='2026-10-12'){ll=[35.55,139.78];place='Haneda';}return {ll,place,zone:date==='2026-10-12'?'Asia/Tokyo':'America/Los_Angeles'};}
 function cache(date){return Store.read('tp-weather-'+date,null);}
 function timeLabel(iso,zone='America/Los_Angeles'){return new Intl.DateTimeFormat('zh-CN',{timeZone:zone,month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
 function weatherLabel(code){return code===0?'晴':code<=3?'多云':code<=48?'雾':code<=67?'雨':code<=77?'雪':code<=82?'阵雨':code<=86?'阵雪':'雷雨';}
 function checks(){return Store.read('tp-condition-checks',{});}
 function sourceCard(id,date){const s=sources.find(s=>s.id===id),checked=checks()[date+':'+id];return `<div class="condition"><strong>${E(s.title)}</strong><p>${E(s.note)}</p><a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">打开官方 / 来源页面 ↗</a><p class="muted">${checked?'你已核对 '+E(timeLabel(checked)):'尚未当天核对'}</p><button class="text-btn" data-check="${id}" data-check-date="${date}">我已核对</button></div>`;}
 function relevant(date){if(date==='2026-09-28')return ['gorge','or-roads'];if(date==='2026-09-29')return ['apple','flavel','or-roads'];if(date==='2026-09-30')return ['tide','or-roads'];if(date==='2026-10-01')return ['ecola','or-roads'];if(['2026-10-05','2026-10-06'].includes(date))return ['ca-roads',date.endsWith('05')?'surf':'mcway'];if(date==='2026-10-03')return ['golden-gate','muir'];return ['ca-roads'];}
 function render(date){if(!date)return;const cfg=config(date),w=cache(date),old=w&&(Date.now()-Date.parse(w.fetchedAt)>6*3600000),err=errors.get(date);let weather=`<strong>🌦 ${E(cfg.place)}</strong><p>${inFlight.has(date)?'正在获取天气…':'天气尚未获取'}</p><p class="muted">${E(err||'联网后刷新；暂无实时读数')}</p>`;
 if(w&&Number.isFinite(w.min)&&Number.isFinite(w.max))weather=`<strong>🌦 ${Math.round(w.min)}–${Math.round(w.max)}°C · ${weatherLabel(w.code)}</strong><p>${E(cfg.place)} · 当天预报${Number.isFinite(w.rain)?` · 降水概率 ${w.rain}%`:''}</p><p class="muted">${old||!navigator.onLine||err?'缓存数据 · ':''}获取于 ${E(timeLabel(w.fetchedAt,cfg.zone))}${old?' · 已超过 6 小时，需更新':''}</p>${err?`<p class="muted">${E(err)}</p>`:''}`;
 const sunset=w?.sunset?.slice(11,16),remain=sunset?TripCore.remaining(date,sunset,new Date(),cfg.zone):'';
 let html=`<div class="conditions-grid"><div class="condition">${weather}<a href="https://forecast.weather.gov/MapClick.php?lat=${cfg.ll[0]}&lon=${cfg.ll[1]}" target="_blank" rel="noopener noreferrer">NWS 官方天气 ↗</a></div><div class="condition"><strong>🌅 日落 ${sunset?E(sunset):'待获取'}</strong><p>${E(remain||cfg.place)}</p><p class="muted">${sunset?'按地点与日期计算 · '+E(cfg.zone):'行程中的日落时刻仅为计划估计'}</p><a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">天气与日落：Open-Meteo</a></div>`;
 html+=relevant(date).map(id=>sourceCard(id,date)).join('');
 if(date==='2026-09-30'){const tide=Store.read('tp-tide-'+date,null);html+=`<div class="condition"><strong>🌊 低潮时间 · 手动核对</strong><p>${tide?E(tide.time)+' · '+E(timeLabel(tide.checkedAt))+' 手动记录':'尚未核对，不显示推测时间'}</p><label>9/30 当地时间 <input type="time" id="tide-time" aria-label="核对后的低潮时间" value="${E(tide?.time||'')}"></label><button class="text-btn" id="save-tide">保存已核对时间</button><p class="muted">仅用于计划；海浪与现场封闭另查。可在官方潮表选适合的低潮时段。</p></div>`;}
 html+=`<div class="condition"><strong>🌧 雨备 / 节奏</strong><p>${date==='2026-09-29'?'两座博物馆优先；风雨大时放弃登塔。':date==='2026-09-30'?'海事博物馆替代东区支线，潮池不可达就远观海滩。':TP.plans[date].region==='ride'?'风雨或能见度不好就压缩路线，保留加油和日落前结束骑行。':'缩短户外停留，不为赶点压缩休息与交通余量。'}</p></div></div>`;$('conditions').innerHTML=html;}
 async function load(date,force=false){const cfg=config(date),c=cache(date);if(!force&&c&&Date.now()-Date.parse(c.fetchedAt)<3600000){render(date);return;}if(inFlight.has(date))return;if(!navigator.onLine){errors.set(date,'离线，实时条件无法更新。');render(date);return;}
 const delta=(Date.parse(date)-Date.parse(TripCore.clock(new Date(),cfg.zone).date))/86400000;if(delta<0||delta>15){errors.set(date,delta<0?'历史日期，仅显示已保存数据；不把当前天气当作当天天气。':'超出 16 天预报范围，临近日期再刷新。');render(date);return;}
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);inFlight.set(date,true);errors.delete(date);if(date===selectedDate)render(date);
 try{const q=new URLSearchParams({latitude:String(cfg.ll[0]),longitude:String(cfg.ll[1]),daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunset',timezone:cfg.zone,start_date:date,end_date:date});const response=await fetch('https://api.open-meteo.com/v1/forecast?'+q,{signal:controller.signal});if(!response.ok)throw Error('weather');const data=await response.json(),daily=data.daily;if(daily?.time?.[0]!==date||!Number.isFinite(daily.temperature_2m_min?.[0])||!Number.isFinite(daily.temperature_2m_max?.[0]))throw Error('data');Store.write('tp-weather-'+date,{min:daily.temperature_2m_min[0],max:daily.temperature_2m_max[0],code:daily.weather_code[0],rain:daily.precipitation_probability_max[0],sunset:daily.sunset[0],fetchedAt:new Date().toISOString()});}
 catch(_){errors.set(date,'天气服务暂不可用；请打开官方天气，已有缓存会保留。');}finally{clearTimeout(timer);inFlight.delete(date);if(date===selectedDate)render(date);}}
 function renderSources(){$('sources').innerHTML=sources.map(s=>`<div class="panel"><h3>${E(s.title)}</h3><span class="tag-kind">${E(s.type)}</span><p class="muted">${E(s.note)}</p><a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">来源 ↗</a></div>`).join('');}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.check){const all=checks();all[b.dataset.checkDate+':'+b.dataset.check]=new Date().toISOString();Store.write('tp-condition-checks',all);render(selectedDate);toast('已记录你的核对时间');}if(b.id==='save-tide'){const value=$('tide-time')?.value;if(!/^\d{2}:\d{2}$/.test(value)){toast('请先输入已查到的低潮时间');return;}Store.write('tp-tide-'+selectedDate,{time:value,checkedAt:new Date().toISOString()});render(selectedDate);toast('低潮时间已保存在本机');}});
 return {load,render,renderSources};
})();
