(()=>{
 let busy=false;
 function message(type,extra={}){return new Promise((resolve,reject)=>{const sw=navigator.serviceWorker.controller;if(!sw){reject(Error('not controlled'));return;}const channel=new MessageChannel(),timer=setTimeout(()=>reject(Error('timeout')),type==='CACHE_REGION'?120000:10000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();resolve(e.data);};sw.postMessage({type,...extra},[channel.port2]);});}
 async function status(){try{const s=await message('STATUS');if(s.error)throw Error(s.error);$('offline-status').textContent=s.ready?'✓ Offline ready · 行程与应用已就绪':'离线资源不完整，请联网重新打开';$('offline-status').className=s.ready?'offline-ok':'offline-warn';$('offline-regions').innerHTML=Object.keys(REGION_NAMES).map(r=>`<p class="muted">${REGION_NAMES[r]}：${s.regions[r]?(r==='bay'||r==='la'?'行程已缓存（无独立地点照片）':'行程 / 地点照片已缓存'):'行程已缓存 · 地点照片未完整缓存'}</p>`).join('')+`<p class="muted">已浏览底图缓存：${s.tiles} 张瓦片（最多 240 张，不保证完整地区覆盖）。</p>`;}catch(_){$('offline-status').textContent='离线资源尚未就绪，请联网等待安装完成后重新检查。';$('offline-status').className='offline-warn';}}
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='check-offline')status();if(b.dataset.cache){if(busy)return;if(!navigator.onLine){toast('请联网后缓存地区照片');return;}busy=true;document.querySelectorAll('[data-cache]').forEach(x=>x.disabled=true);$('offline-status').textContent='正在缓存 '+REGION_NAMES[b.dataset.cache]+' 的行程照片…';try{const r=await message('CACHE_REGION',{region:b.dataset.cache});toast(r.error||r.failed?`缓存未完整完成${r.failed?'，'+r.failed+' 张照片失败':''}，可重试`:'地区资源已缓存；底图仍仅限已浏览部分');}catch(_){toast('缓存未完成，请联网重试');}finally{busy=false;document.querySelectorAll('[data-cache]').forEach(x=>x.disabled=false);status();}}});
 if(!('serviceWorker' in navigator)){$('offline-status').textContent='当前浏览器不支持离线缓存，请使用 HTTPS 网站。';return;}
 navigator.serviceWorker.addEventListener('controllerchange',()=>{status();});
 navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(reg=>{reg.update().catch(()=>{});return navigator.serviceWorker.ready;}).then(()=>status()).catch(()=>{$('offline-status').textContent='离线安装失败，请联网重试；当前页面仍可使用。';});
})();
