const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){const events={},buckets=new Map(),scope='https://example.test/tidepool/';function key(s){return new URL(typeof s==='string'?s:s.url,scope).href;}
 const caches={async open(name){if(!buckets.has(name))buckets.set(name,new Map());const data=buckets.get(name);return {async addAll(files){for(const f of files)data.set(key(f),new Response('asset'));},async match(f){return data.get(key(f))?.clone();},async put(f,r){data.set(key(f),r.clone());},async keys(){return [...data.keys()].map(url=>({url}));},async delete(f){return data.delete(key(f));}};},async keys(){return [...buckets.keys()];},async delete(k){return buckets.delete(k);}};
 const context={URL,Response,Promise,location:new URL(scope),fetch:async()=>new Response('online'),caches,self:{registration:{scope},addEventListener:(name,fn)=>events[name]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),context);
 async function event(name,props={}){let work;events[name]({...props,waitUntil:p=>work=p,respondWith:p=>work=p});return await work;}
 return {event,caches,buckets,context,async message(data){let reply;await event('message',{data,ports:[{postMessage:r=>reply=r}]});return reply;}};}
test('atomic shell includes all sources and legacy booking replacement; old private page caches removed',async()=>{const h=harness();await h.caches.open('tp-old-private');await h.caches.open('unrelated-app');await h.event('install');await h.event('activate');assert(!(await h.caches.keys()).includes('tp-old-private'));assert((await h.caches.keys()).includes('unrelated-app'));const status=await h.message({type:'STATUS'});assert.equal(status.ready,true);h.context.fetch=async()=>{throw Error('offline');};const result=await h.event('fetch',{request:{method:'GET',mode:'navigate',url:'https://example.test/tidepool/booking.html'}});assert.equal(await result.text(),'asset');const asset=await h.event('fetch',{request:{method:'GET',mode:'cors',url:'https://example.test/tidepool/data/plans.js'}});assert.equal(await asset.text(),'asset');});
test('region offline status reflects missing photos and catches network errors',async()=>{const h=harness();await h.event('install');assert.equal((await h.message({type:'STATUS'})).regions.portland,false);h.context.fetch=async()=>{throw Error('offline');};const fail=await h.message({type:'CACHE_REGION',region:'portland'});assert.equal(fail.failed,fail.total);assert.equal((await h.message({type:'STATUS'})).regions.portland,false);h.context.fetch=async()=>new Response('photo');assert.equal((await h.message({type:'CACHE_REGION',region:'portland'})).failed,0);assert.equal((await h.message({type:'STATUS'})).regions.portland,true);});
test('private imports and foreign API calls are never cached by worker',async()=>{const h=harness();await h.event('install');assert.equal(await h.event('fetch',{request:{method:'GET',mode:'cors',url:'https://example.test/tidepool/private-details.json'}}),undefined);assert.equal(await h.event('fetch',{request:{method:'GET',mode:'cors',url:'https://api.open-meteo.com/v1/forecast'}}),undefined);});
